<?php
/**
 * Configuration file for Organic Lingua API
 *
 * @package     Organic API
 * @version     1.2 - 2013-04-04 | 1.1 - 2013-03-05 | 1.0 - 2012-10-08
 * 
 * @author      David Baños Expósito
 */

namespace Ieru\Ieruapis\Organic\Config;

class Config
{
	private $_routes;
	private $_autolang;

	/**
	 * Returns the routes allowed in this API
	 *
	 * @return array
	 */
	public function & get_routes ()
	{
		if ( !$this->_routes )
		{
			$this->_routes['POST'][] = array( '/resources',     'controller'=>'OrganicAPI#fetch_resources' );
			$this->_routes['GET'][]  = array( '/resources/:id', 'controller'=>'OrganicAPI#fetch_resource' );
			$this->_routes['GET'][]  = array( '/search',        'controller'=>'OrganicAPI#get_search' );
			$this->_routes['GET'][]  = array( '/login',         'controller'=>'AuthAPI#login' );
			$this->_routes['GET'][]  = array( '/logout',        'controller'=>'AuthAPI#logout' );
			$this->_routes['POST'][] = array( '/register',      'controller'=>'AuthAPI#register' );
		}
		return $this->_routes;
	}

	/**
	 * Returns the routes allowed in this API
	 *
	 * @return array
	 */
	public function & get_autolang ()
	{
		if ( !$this->_autolang )
		{
                  $this->_autolang[] = 'en'; # English
			$this->_autolang[] = 'de'; # German
			$this->_autolang[] = 'fr'; # French
			$this->_autolang[] = 'es'; # Spanish
			$this->_autolang[] = 'it'; # Italian
			$this->_autolang[] = 'el'; # Greek
			$this->_autolang[] = 'tr'; # Turkish
			$this->_autolang[] = 'lv'; # Latvian
			$this->_autolang[] = 'et'; # Estonian
			$this->_autolang[] = 'pl'; # Polish
			$this->_autolang[] = 'pt'; # Portuguese
		}
		return $this->_autolang;
	}

	/**
	 * Retuns an array with all the possible ISO 639-2 lang specification
	 *
	 * @return array An array with the 2 letter ISO language codes
	 */
	public function get_iso_lang ()
	{
		return array(
            'aa' => 'Afar',
            'ab' => 'Abkhaz',
            'ae' => 'Avestan',
            'af' => 'Afrikaans',
            'ak' => 'Akan',
            'am' => 'Amharic',
            'an' => 'Aragonese',
            'ar' => 'Arabic',
            'as' => 'Assamese',
            'av' => 'Avaric',
            'ay' => 'Aymara',
            'az' => 'Azerbaijani',
            'ba' => 'Bashkir',
            'be' => 'Belarusian',
            'bg' => 'Bulgarian',
            'bh' => 'Bihari',
            'bi' => 'Bislama',
            'bm' => 'Bambara',
            'bn' => 'Bengali',
            'bo' => 'Tibetan',
            'br' => 'Breton',
            'bs' => 'Bosnian',
            'ca' => 'Catalan',
            'ce' => 'Chechen',
            'ch' => 'Chamorro',
            'co' => 'Corsican',
            'cr' => 'Cree',
            'cs' => 'Czech',
            'cu' => 'Old Slavonic',
            'cv' => 'Chuvash',
            'cy' => 'Welsh',
            'da' => 'Danish',
            'de' => 'German',
            'dv' => 'Divehi',
            'dz' => 'Dzongkha',
            'ee' => 'Ewe',
            'el' => 'Greek',
            'en' => 'English',
            'eo' => 'Esperanto',
            'es' => 'Spanish',
            'et' => 'Estonian',
            'eu' => 'Basque',
            'fa' => 'Persian',
            'ff' => 'Fula',
            'fi' => 'Finnish',
            'fj' => 'Fijian',
            'fo' => 'Faroese',
            'fr' => 'French',
            'fy' => 'Western Frisian',
            'ga' => 'Irish',
            'gd' => 'Scottish Gaelic',
            'gl' => 'Galician',
            'gn' => 'GuaranÃ­',
            'gu' => 'Gujarati',
            'gv' => 'Manx',
            'ha' => 'Hausa',
            'he' => 'Hebrew',
            'hi' => 'Hindi',
            'ho' => 'Hiri Motu',
            'hr' => 'Croatian',
            'ht' => 'Haitian',
            'hu' => 'Hungarian',
            'hy' => 'Armenian',
            'hz' => 'Herero',
            'ia' => 'Interlingua',
            'id' => 'Indonesian',
            'ie' => 'Interlingue',
            'ig' => 'Igbo',
            'ii' => 'Nuosu',
            'ik' => 'Inupiaq',
            'io' => 'Ido',
            'is' => 'Icelandic',
            'it' => 'Italian',
            'iu' => 'Inuktitut',
            'ja' => 'Japanese (ja)',
            'jv' => 'Javanese (jv)',
            'ka' => 'Georgian',
            'kg' => 'Kongo',
            'ki' => 'Kikuyu',
            'kj' => 'Kwanyama',
            'kk' => 'Kazakh',
            'kl' => 'Kalaallisut',
            'km' => 'Khmer',
            'kn' => 'Kannada',
            'ko' => 'Korean',
            'kr' => 'Kanuri',
            'ks' => 'Kashmiri',
            'ku' => 'Kurdish',
            'kv' => 'Komi',
            'kw' => 'Cornish',
            'ky' => 'Kirghiz, Kyrgyz',
            'la' => 'Latin',
            'lb' => 'Luxembourgish',
            'lg' => 'Luganda',
            'li' => 'Limburgish',
            'ln' => 'Lingala',
            'lo' => 'Lao',
            'lt' => 'Lithuanian',
            'lu' => 'Luba-Katanga',
            'lv' => 'Latvian',
            'mg' => 'Malagasy',
            'mh' => 'Marshallese',
            'mi' => 'Maori',
            'mk' => 'Macedonian',
            'ml' => 'Malayalam',
            'mn' => 'Mongolian',
            'mr' => 'Marathi',
            'ms' => 'Malay',
            'mt' => 'Maltese',
            'my' => 'Burmese',
            'na' => 'Nauru',
            'nb' => 'Norwegian',
            'nd' => 'North Ndebele',
            'ne' => 'Nepali',
            'ng' => 'Ndonga',
            'nl' => 'Dutch',
            'nn' => 'Norwegian Nynorsk',
            'no' => 'Norwegian',
            'nr' => 'South Ndebele',
            'nv' => 'Navajo, Navaho',
            'ny' => 'Chichewa',
            'oc' => 'Occitan',
            'oj' => 'Ojibwe',
            'om' => 'Oromo',
            'or' => 'Oriya',
            'os' => 'Ossetian',
            'pa' => 'Panjabi',
            'pi' => 'Pali',
            'pl' => 'Polish',
            'ps' => 'Pashto, Pushto',
            'pt' => 'Portuguese',
            'qu' => 'Quechua',
            'rm' => 'Romansh',
            'rn' => 'Kirundi',
            'ro' => 'Romanian',
            'ru' => 'Russian',
            'rw' => 'Kinyarwanda',
            'sa' => 'Sanskrit',
            'sc' => 'Sardinian',
            'sd' => 'Sindhi',
            'se' => 'Northern Sami',
            'sg' => 'Sango',
            'si' => 'Sinhala',
            'sk' => 'Slovak',
            'sl' => 'Slovene',
            'sm' => 'Samoan',
            'sn' => 'Shona',
            'so' => 'Somali',
            'sq' => 'Albanian',
            'sr' => 'Serbian',
            'ss' => 'Swati',
            'st' => 'Southern Sotho',
            'su' => 'Sundanese',
            'sv' => 'Swedish',
            'sw' => 'Swahili',
            'ta' => 'Tamil',
            'te' => 'Telugu',
            'tg' => 'Tajik',
            'th' => 'Thai',
            'ti' => 'Tigrinya',
            'tk' => 'Turkmen',
            'tl' => 'Tagalog',
            'tn' => 'Tswana',
            'to' => 'Tonga',
            'tr' => 'Turkish',
            'ts' => 'Tsonga',
            'tt' => 'Tatar',
            'tw' => 'Twi',
            'ty' => 'Tahitian',
            'ug' => 'Uighur',
            'uk' => 'Ukrainian',
            'ur' => 'Urdu',
            'uz' => 'Uzbek',
            've' => 'Venda',
            'vi' => 'Vietnamese',
            'vo' => 'Volapak',
            'wa' => 'Walloon',
            'wo' => 'Wolof',
            'xh' => 'Xhosa',
            'yi' => 'Yiddish',
            'yo' => 'Yoruba',
            'za' => 'Zhuang',
            'zh' => 'Chinese',
            'zu' => 'Zulu',
        );
	}

	/**
	 * Get the data for connecting with the database
	 *
	 * @return array The data needed for connecting with the IEEE LOM database
	 */
	public function get_db_info ()
	{
		return array( 
			'host'=>'localhost',
			'database'=>'lomsqldat',
			'username'=>'root',
			'password'=>''
		);
	}

      /**
       * Get the data for connecting with the OAUTH database
       *
       * @return array The data needed for connecting with the database
       */
      public function get_db_oauth_info ()
      {
            return array( 
                  'host'=>'localhost',
                  'database'=>'ieru_organic_lingua_oauth',
                  'username'=>'root',
                  'password'=>''
            );
      }

      /**
       * Returns the IP of the server of the Analytics API
       *
       * @return string
       */
      public function get_analytics_server_ip ()
      {
            return 'http://lingua.dev';
      }

      /**
       *
       */
      public function get_resources_langs ()
      {
return array(
'http://www.fondazioneslowfood.it/filemanager/I%20progetti/Mille%20orti%20in%20Africa/educa/INGL-sowing.pdf'=>array('en','pt','fr'),
'http://www.slowfood.com/education/pagine/eng/pagina.lasso?-id_pg=25'=>array('en','fr','de','es','pt','ro','pl','ru','it'),
'http://www1.eere.energy.gov/education/lessonplans/plans.aspx?id=256'=>array('en','es'),
'http://www.slowfood.com/education/filemanager/resources/Origini_Gusto_eng.pdf'=>array('en','it','de','fr','es','pt','ru','ro','pl'),
'http://www.fondazioneslowfood.it/pagine/eng/orti/pagina.lasso?-id_pg=33'=>array('en','fr','it','pt'),
'http://www.fondazioneslowfood.it/filemanager/I%20progetti/Mille%20orti%20in%20Africa/educa/INGL-compost.pdf'=>array('en','fr','pt'),
'http://www.slowfood.com/education/filemanager/resources/Sense_eng.pdf'=>array('en','it','de','es','pt','ru','ro','pl'),
'http://www.fondazioneslowfood.it/filemanager/I%20progetti/Mille%20orti%20in%20Africa/educa/INGL-kitchen.pdf'=>array('en','fr','pt'),
'http://oe.confolio.org/scam/34/resource/120'=>array('no','en'),
'http://oe.confolio.org/scam/34/resource/186'=>array('en','es'),
'http://informatics.aua.gr:8080/scam/3/resource/49'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/305'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1529&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=42&tpl=dc&glang=eng'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/23'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=560&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=558&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1031&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/22'=>array('ro','en'),
'http://www.organicagcentre.ca/Docs/FiBL_High-bushBerries_nov10-05.pdf'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/290'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1219&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1256&tpl=ieee&glang=rom&glang=eng'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/156'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/72'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/3'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/164'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/41'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/14'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1048&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=958&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/31'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/24'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=472&tpl=dc'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1208&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1187&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1109&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/26'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/127'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/67'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=547&tpl=dc&glang=rom'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/191'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=849&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1420&tpl=ieee&glang=rom&glang=rom&glang=eng'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/149'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/65'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/21'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1526&tpl=dc&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=528&tpl=iee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/110'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/155'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/289'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/34'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/43'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/304'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=514&tpl=dc&glang=rom'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/150'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=411&tpl=dc'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/128'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/104'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/162'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=472&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1151&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=527&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1721&tpl=dc'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1046&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/121'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=546&tpl=dc&glang=rom'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/106'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/153'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/45'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/33'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/63'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/51'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=445&tpl=dc'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/286'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/301'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/48'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1466&tpl=dc&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1263&tpl=ieee'=>array('en','ro'),
'http://anrcatalog.ucdavis.edu/pdf/7248.pdf'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1105&tpl=ieee&glang=eng&glang=rom&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=654&tpl=ieee&glang=ell'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1050&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1122&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1428&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/291'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/36'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/54'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/136'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1335&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/161'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/5'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=550&tpl=dc'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=548&tpl=dc&glang='=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/160'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/293'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/306'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1027&tpl=ieee&glang=eng'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/287'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/135'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/167'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/295'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/35'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/70'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/17'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1468&tpl=dc&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1435&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/30'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=555&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=409&tpl=dc'=>array('en','ro'),
'http://anrcatalog.ucdavis.edu/pdf/7250.pdf'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=57&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1045&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1101&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/119'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1049&tpl=ieee'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/303'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1465&tpl=dc&glang=eng'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=443&tpl=dc&glang=rom'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=56&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/4'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/132'=>array('ro','en'),
'http://www.organicagcentre.ca/Docs/FiBL_WeedCtrl_Vegetables.pdf'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1453&tpl=ieee'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=433&tpl=dc'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=55&tpl=ieee&glang=eng'=>array('en','ro'),
'http://www.gnb.ca/0174/01740002-e.asp'=>array('en','ro'),
'http://www.organicagcentre.ca/Docs/FiBL_StandardOrchards_nov10-05.pdf'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/151'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/9'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/66'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/200'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/137'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=1584&tpl=dc&glang=rom'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/158'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/298'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=529&tpl=ieee'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/284'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/163'=>array('ro','en'),
'http://informatics.aua.gr:8080/scam/3/resource/120'=>array('ro','en'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=410&tpl=dc'=>array('en','ro'),
'http://www.bioagro.gr/modules/contentpro/index.php?op=showentry&id=449&tpl=dc&glang=rom'=>array('en','ro'),
'http://informatics.aua.gr:8080/scam/3/resource/61'=>array('en','ro'),
'http://www.fleisch-teilstuecke.at/en/ts_flash_pute/flash/truthahn/'=>array('de','en'),
'http://www.oengene.at'=>array('de','en'),
'http://www.fleisch-teilstuecke.at/de/ts_flash_lamm/flash/lamm/'=>array('de','en'),
'http://www.fleisch-teilstuecke.at/ts_flash_rind/flash/rind/'=>array('de','en'),
'http://131.130.57.239/LTER_cms/index.php?page=home&f=1&i=home'=>array('en','de'),
'http://www.fleisch-teilstuecke.at/en/ts_flash_huhn/flash/huhn/'=>array('de','en'),
'http://publikationen.lebensministerium.at/filemanager/download/51416'=>array('de','en'),
'http://www.fleisch-teilstuecke.at/en/ts_flash_kalb/flash/kalb/'=>array('de','en'),
'http://www.fleisch-teilstuecke.at/'=>array('de','en'),
'http://www.fleisch-teilstuecke.at/en/ts_flash_schwein/flash/schwein/'=>array('de','en'),
'http://oe.confolio.org/scam/31/resource/142'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/54'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/39'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/50'=>array('en','hu'),
'http://www.okogarancia.hu'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/53'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/281'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/48'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/45'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/43'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/46'=>array('en','hu'),
'http://www.hortobagy.eu'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/40'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/49'=>array('en','hu'),
'http://anubis.kee.hu'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/57'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/42'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/52'=>array('en','hu'),
'http://www.mgegodollo.hu'=>array('hu','en'),
'http://oe.confolio.org/scam/31/resource/41'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/58'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/111'=>array('en','hu'),
'http://oe.confolio.org/scam/31/resource/262'=>array('hu','de'),
'http://oe.confolio.org/scam/31/resource/51'=>array('en','hu'),
'http://ec.europa.eu/agriculture/organic/home_el'=>array('el','de','fi','ro'),
'http://www.ea.gr/ep/organic/content/'=>array('en','el'),
'http://connect.ea.gr/georgas_vine/'=>array('en','el'),
'http://www.ea.gr/ep/organic/content/Presentation_of_the__101011191245679262413.html'=>array('en','el'),
'http://oe.confolio.org/scam/32/resource/9'=>array('en','et'),
'http://www.emu.ee'=>array('en','et'),
'http://www.eko-connect.org/'=>array('de','en','pl'),
'http://www.pma.agri.ee/index.php?id=104&sub=128'=>array('et','en'),
'http://www.metla.fi/index-en.html'=>array('en','fi','sv','de'),
'http://www.mcpfe.org/'=>array('en','de','ru','es'),
'http://www.organicxseeds.com/oxs/do/Login?paramCountry=188'=>array('en','de','es'),
'http://www.cha-hort.com/index.htm'=>array('en','fr','es'),
'http://reports.eea.europa.eu/climate_report_2_2004/en/index_html'=>array('en','cs','da','nl','et','fi','fr','de','el','hu','it','no','pl','pt','ro','ru','sk','es','sv'),
'http://www.epa.gov/oppefed1/aceto/index.htm'=>array('en','eng;'),
'http://ethesis.helsinki.fi/julkaisut/maa/mekol/vk/linkosalo/'=>array('en','fi'),
'http://www.ukredsquirrels.org/'=>array('en','eng'),
'http://www.agr.gc.ca/index_e.php'=>array('en','fr'),
'http://www.adfg.state.ak.us/pubs/afrb/afrbhome.php'=>array('en','eng'),
'http://www.oznet.ksu.edu/library/hort2/mf312.pdf'=>array('en','eng;'),
'http://www.fao.org/foodclimate/conference/en/'=>array('en','fr','es'),
'http://www.fao.org/docrep/003/y1860e/y1860e00.htm'=>array('en','fr','es'),
'http://www.coa.lsu.edu/'=>array('en','eng;'),
'http://www.fao.org/docrep/010/i0112e/i0112e00.htm'=>array('en','fr','es'),
'http://www.rirdc.gov.au/reports/NAP/00-188.htm#contents'=>array('en','eng;'),
'http://www.fara-africa.org/'=>array('en','fr'),
'http://www.fao.org/docrep/w3094e/w3094e00.htm'=>array('en','fr'),
'http://www.fao.org/infoods/'=>array('en','fr','es'),
'http://www.ciheam.org/index.php'=>array('fr','en'),
'http://www.merid.org/fs-agbiotech/index.php'=>array('en','fr'),
'http://www.mtt.fi/english/'=>array('en','fi','sv'),
'http://pigtrop.cirad.fr/home'=>array('en','fr','es'),
'http://www.warda.cgiar.org/warda1/index.htm'=>array('en','fr'),
'http://www.cemagref.fr/English/'=>array('en','fr'),
'http://tech.groups.yahoo.com/group/ifl-tech2000/'=>array('en','fr','de','es','pt','nl'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/effluent.pdf'=>array('en','eng;'),
'http://www.iefc.net/'=>array('en','fr','pt','es'),
'http://www.nasdonline.org/'=>array('en','es'),
'http://www.inspection.gc.ca/english/toce.shtml'=>array('en','eng'),
'http://www.fuw.org.uk/'=>array('en','cy'),
'http://www.sunflowernsa.com/default.asp'=>array('en','es'),
'http://www.kslab.ksla.se/'=>array('en','sv'),
'http://www.fadr.msu.ru/fadr_e/index_e.html'=>array('en','ru'),
'http://www.foodhaccp.com/'=>array('en','fr'),
'http://www.cameraria.de/cameraria_e.html'=>array('en','de'),
'http://www.agromisa.org/'=>array('en','nl'),
'http://www.fao.org/docrep/W5183E/W5183E00.htm'=>array('en','fr'),
'http://www.fsis.usda.gov/'=>array('en','es'),
'http://www.inspection.gc.ca/english/fssa/labeti/guide/toce.shtml'=>array('en','fr'),
'http://www.fao.org/organicag/'=>array('en','fr','es'),
'http://www.fao.org/forestry/cpf-climatechange/en/'=>array('en','fr','es'),
'http://www.croptrust.org/'=>array('en','es'),
'http://www.cra.wallonie.be/'=>array('en','fr'),
'http://www.ecn.nl/en/bkm/'=>array('en','nl'),
'http://www.fao.org/WAICENT/faoinfo/economic/giews/english/fo/index.htm'=>array('en','fr','es'),
'http://www.rothamsted.bbsrc.ac.uk/aen/links.htm'=>array('en','eng;'),
'http://www.cipotato.org/'=>array('en','es'),
'http://www.bats.ch/bats/en/index.php'=>array('en','de'),
'http://www.echonet.org/'=>array('en','fr','es'),
'http://www.efsa.europa.eu/EFSA/efsa_locale-1178620753812_1178699572768.htm'=>array('en','de','fr'),
'http://www.cgiar.org/'=>array('en','es','fr','de','ru'),
'http://www.extension.iastate.edu/foodsafety/'=>array('en','es'),
'http://www.fao.org/docrep/005/y3918e/y3918e00.htm'=>array('en','fr','it','es'),
'http://www.agropolis.org/'=>array('en','fr'),
'http://www.toscanaolives.com.au/index.htm'=>array('en','eng'),
'http://www.biosaline.org/'=>array('en','fr'),
'http://www.cimmyt.org/'=>array('en','es'),
'http://www.fao.org/docrep/T0522E/T0522E00.htm'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Crustacea_web_final.pdf'=>array('en','eng;'),
'http://www.ces.ncsu.edu/depts/pp/notes/oldnotes/vg16.htm'=>array('fi','en'),
'http://www.reading.ac.uk/soilscience/'=>array('en','eng;'),
'http://www.oznet.ksu.edu/library/hort2/mf2609.pdf'=>array('en','eng;'),
'http://www.abdn.ac.uk/agfor/agriculture/index.shtml'=>array('en','eng;'),
'http://ec.europa.eu/agriculture/envir/report/en/index.htm'=>array('en','fr','de'),
'http://www.ifn.fr/spip/sommaire.php3?lang=en'=>array('en','fr'),
'http://www.apiservices.com/'=>array('en','fr','es','de'),
'http://www.fao.org/docrep/x2950e/X2950e00.htm'=>array('en','fr','es','ar'),
'http://www.smhi.se/en'=>array('en','sv'),
'http://www.fao.org/docrep/009/A0699e/A0699e00.htm'=>array('en','fr','es'),
'http://www.scidev.net/en/agriculture-and-environment/gm-crops/'=>array('en','fr','es'),
'http://www.ipcc.ch/'=>array('en','fr','ru','es'),
'http://www.nativefish.org/'=>array('en','eng; eng'),
'http://www.iccat.int/en/'=>array('en','fr','es'),
'http://www.fontagro.org/'=>array('en','es'),
'http://www.ars.usda.gov/main/site_main.htm?modecode=54280500'=>array('en','es'),
'http://www.pesticides.gov.uk/environment.asp?id=504'=>array('en','eng'),
'http://www.omafra.gov.on.ca/english/livestock/sheep/facts/eweflock.htm'=>array('en','fr'),
'http://welcome.warnercnr.colostate.edu/frws-home/index.php'=>array('en','eng;'),
'http://www.ictsd.org/'=>array('en','zh'),
'http://www.fao.org/docrep/w9900e/w9900e00.htm'=>array('en','fr','es'),
'http://meteo.infospace.ru/main.htm'=>array('en','ru'),
'http://www.cta.int/en'=>array('en','fr'),
'http://www.lelait-journal.org/'=>array('en','fr'),
'http://www.oznet.ksu.edu/library/hort2/mf669.pdf'=>array('en','eng;'),
'http://www.cgn.wur.nl/UK/CGN+Plant+Genetic+Resources/'=>array('en','nl'),
'http://www.fao.org/docrep/006/y4997e/y4997e00.htm'=>array('en','fr','es'),
'http://www.endure-network.eu/'=>array('en','da','nl','fr','de','it'),
'http://www.icrisat.org/'=>array('en','fr'),
'http://www.ibles.waw.pl/sylwan/index.html'=>array('en','eng;'),
'http://www.oznet.ksu.edu/library/LVSTK2/mf2336.pdf'=>array('en','eng;'),
'http://europa.eu/legislation_summaries/food_safety/index_en.htm'=>array('en','da','nl','fi','fr','de','el','it','pt','es','sv'),
'http://www.nicyra.org/'=>array('en','eng;'),
'http://www.fao.org/wfs/index_en.htm'=>array('en','fr','es'),
'http://engwww.sik.se/'=>array('en','sv'),
'http://www.forac.ulaval.ca/index.php?&L=1'=>array('en','fr'),
'http://www.matforsk.no/web/home.nsf/HjemE/$First?OpenDocument'=>array('en','no','eng;'),
'http://sdgateway.net/'=>array('en','fr','es'),
'http://www.ipmcenters.org/cropprofiles/docs/MTmustard.html'=>array('en','eng'),
'http://www.copa-cogeca.be/'=>array('en','fr','de','it','pl','es'),
'http://www.ortohum.gov.tr/english/index.htm'=>array('en','tr'),
'http://www.oznet.ksu.edu/library/hort2/mf2605.pdf'=>array('en','eng;'),
'http://www.euacpcommodities.eu/en'=>array('en','fr'),
'http://www.oryza.com/'=>array('en','es'),
'http://www.defra.gov.uk/animalh/diseases/notifiable/ai/pdf/separating.pdf'=>array('en','eng;'),
'http://www.fao.org/WAICENT/FAOINFO/SUSTDEV/Welcome_.htm'=>array('en','fr','es'),
'http://www.defra.gov.uk/farm/organic/policy/actionplan/pdf/org58.pdf'=>array('en','eng;'),
'http://www.fao.org/es/ESS/asil/default.asp'=>array('en','fr','es'),
'http://www.npa-uk.org.uk/'=>array('en','eng;'),
'http://www.geru.ucl.ac.be/index_english.htm'=>array('en','fr'),
'http://www.itc.nl/~rossiter/teach/ssm/SSM_LectureNotes2.pdf'=>array('en','eng;'),
'http://www.fao.org/avianflu/en/index.html'=>array('en','fr','es'),
'http://www.iol.uni-bonn.de/index2_e.htm'=>array('en','de'),
'http://forestry.krc.karelia.ru/index.php?plang=e'=>array('en','ru'),
'http://www.naturland.de/welcome.html'=>array('en','de','es'),
'http://orgprints.org/'=>array('en','de'),
'http://www.idrc.ca/en/ev-29312-201-1-DO_TOPIC.html'=>array('en','fr','es'),
'http://ipmworld.umn.edu/'=>array('en','es'),
'http://www.positivelycoffee.org/'=>array('en','es','fr','pt','eng'),
'http://www.fao.org/docrep/x4400e/x4400e00.htm'=>array('en','fr','es'),
'http://ec.europa.eu/research/leaflets/food_safety/index_en.html'=>array('en','et','fi','da','fr','de','el','hu','es','sv','pt'),
'http://www.fao.org/'=>array('en','fr','ru','es'),
'http://www.jma.go.jp/jma/indexe.html'=>array('en','ja'),
'http://www.ipfsaph.org/'=>array('en','fr','es'),
'http://www.codexalimentarius.net/web/index_en.jsp'=>array('en','fr','es'),
'http://www.bomengids.nl/uk/hoofdsleutel.html'=>array('en','nl'),
'http://www.nationaldairycouncil.org/Pages/Home.aspx'=>array('en','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Mussel%20Factsheet2%20A4s.pdf'=>array('en','eng;'),
'http://www.ifoam.org/'=>array('en','es','de','ru'),
'http://www-infocris.iaea.org/EN/'=>array('en','es'),
'http://www.pfaf.org/index.html'=>array('en','da','fr','de','it','nl','es'),
'http://www.oznet.ksu.edu/library/hort2/mf2579.pdf'=>array('en','eng;'),
'http://www.fao.org/docrep/009/a0645e/a0645e00.htm'=>array('en','fr','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Fish%20and%20Shellfish%20Identification.pdf'=>array('en','eng;'),
'http://www.wdt.qc.ca/'=>array('en','fr'),
'http://www.intute.ac.uk/intoai/oai2.php?verb=GetRecord&identifier=oai:intute.ac.uk:20080729-12301551&metadataPrefix=rdn_dc'=>array('en','eng;'),
'http://www.plantprotection.org/'=>array('en','de','fr'),
'http://www.agroscope.admin.ch/imkerei/00316/00329/index.html?lang=en'=>array('en','fr','de','it'),
'http://eur-lex.europa.eu/en/legis/latest/chap03.htm'=>array('en','cs','da','nl','et','fr','fi','de','el','hu','it','pl','pt','ro','ru','sk','es','sv'),
'http://www.umass.edu/nre/'=>array('en','eng;'),
'http://www.fao.org/fi/figis/'=>array('en','fr','es'),
'http://www.agriscape.com/'=>array('en','fr','es'),
'http://www.fao.org/docrep/011/i0350e/i0350e00.htm'=>array('en','fr','ru','es'),
'http://www.defra.gov.uk/environment/acre/advice/pdf/acre_advice56.pdf'=>array('en','eng;'),
'http://www.fao.org/forestry/39135/en/'=>array('en','es'),
'http://www.fao.org/docrep/W2598E/w2598e00.htm'=>array('en','es'),
'http://ec.europa.eu/agriculture/organic/home_en'=>array('en','et','de','el','hu','ro','es','sv'),
'http://www.defra.gov.uk/farm/wildlife/weeds/pdf/ragwort-dispose.pdf'=>array('en','eng;'),
'http://www.scielo.br/scielo.php?script=sci_serial&pid=1516-635X&lng=en&nrm=iso'=>array('en','pt','es'),
'http://www.europarl.europa.eu/workingpapers/forest/eurfo_en.htm'=>array('en','fr'),
'http://www.defra.gov.uk/animalh/diseases/zoonoses/conference/bookabs.PDF'=>array('en','eng;'),
'http://www.flaxcouncil.ca/english/index.jsp'=>array('en','fr','de'),
'http://www.foodfirst.co.uk/'=>array('en','eng;'),
'http://www.alcohol-aware.org/'=>array('en','eng; eng'),
'http://www.life.uiuc.edu/delucia/Luo%20et%20al.%20GBC%202003.pdf'=>array('en','eng'),
'http://www.scielo.br/scielo.php?script=sci_serial&pid=0006-8705&lng=en&nrm=iso'=>array('en','pt','es'),
'http://www.terredesemences.com/'=>array('en','fr'),
'http://www.isaaa.org/kc/cropbiotechupdate/'=>array('en','fr','it','es'),
'http://www.fao.org/docrep/009/a0750e/a0750e00.htm'=>array('en','fr','es'),
'http://www.ars.usda.gov/main/site_main.htm?modecode=19350000'=>array('en','es'),
'http://www.iww.uni-freiburg.de/institute-for-forest-growth/view?set_language=en'=>array('en','de'),
'http://ec.europa.eu/agriculture/foodqual/quali1_en.htm'=>array('en','de','fr'),
'http://www.efsa.europa.eu/'=>array('en','de','fr'),
'http://mulch.mannlib.cornell.edu/'=>array('en','es'),
'http://www.inspection.gc.ca/'=>array('en','fr'),
'http://www2.hud.ac.uk/sas/nuthealth/index.php'=>array('en','eng;'),
'http://www.bio-suisse.ch/en/home.php'=>array('en','fr','de','it','es'),
'http://www.fao.org/forestry/livelihoods/en/'=>array('en','fr','es'),
'http://rgp.dna.affrc.go.jp/index.html'=>array('en','ja'),
'http://www.eea.europa.eu/'=>array('en','cs','da','de','et','fi','fr','el','hu','it','no','pl','pt','ro','sk','es','sv'),
'http://www.woodland-wildflowers.org.uk/'=>array('en','eng;'),
'http://www.fao.org/ag/AGP/AGPP/IPM/gipmf/index.htm'=>array('en','eng;'),
'http://www.grain.org/front/index.cfm'=>array('en','fr','es'),
'http://www.fao.org/docrep/006/y5160e/y5160e00.htm'=>array('en','fr','es'),
'http://www.ifpri.org/pubs/fpr/pr18.asp'=>array('en','es'),
'http://www.lubilosa.org/'=>array('en','fr'),
'http://www.mv.slu.se/'=>array('en','sv'),
'http://www.fao.org/docrep/008/a0050e/a0050e00.htm'=>array('en','fr','es'),
'http://www.fidafrique.net/?lang=en'=>array('en','fr'),
'http://bananas.bioversityinternational.org/'=>array('en','fr','es'),
'http://www.fao.org/DOCREP/003/W9634E/W9634E00.HTM'=>array('en','fr','es'),
'http://www.ars.usda.gov/News/docs.htm?docid=15572'=>array('en','es'),
'http://www.ars.usda.gov/is/AR/'=>array('en','es'),
'http://www.ppic.org.uk/'=>array('en','eng;'),
'http://www.worldbank.org/'=>array('en','fr','es','ru'),
'http://www.genres.de/genres-e.htm'=>array('en','de'),
'http://www.oznet.ksu.edu/library/hort2/mf2616.pdf'=>array('en','eng;'),
'http://www.fas.usda.gov/agx/organics/index.htm'=>array('en','eng'),
'http://www.aushs.org.au/'=>array('en','eng;'),
'http://inspection.gc.ca/english/anima/disemala/fmdfa/fmdfae.shtml'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/GMPG_Bivalves.pdf'=>array('en','eng;'),
'http://www.wiso.boku.ac.at/bwfh.html?&L=1'=>array('en','de'),
'http://www.grainscanada.gc.ca/'=>array('en','fr'),
'http://www.jti.se/index.php?page=english'=>array('en','sv'),
'http://www.cdn.ca/'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Discarding%20fact%20sheet.pdf'=>array('en','eng;'),
'http://www.spannocchia.org/'=>array('en','it'),
'http://fis.com/'=>array('en','es'),
'http://ec.europa.eu/agriculture/publi/agrep2000/index_en.htm'=>array('en','es','de','sv'),
'http://nfdp.ccfm.org/'=>array('en','fr'),
'http://www.nfp-facility.org/home/en/'=>array('en','fr','es'),
'http://ec.europa.eu/agriculture/rica/index_en.cfm'=>array('en','fr','de'),
'http://www.calfnotes.com/'=>array('en','pt','es'),
'http://www.fao.org/DOCREP/004/X3307E/X3307E00.HTM'=>array('en','fr','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Haddock%20v%201.1.pdf'=>array('en','eng;'),
'http://www.fao.org/DOCREP/003/Y1515B/y1515b13.htm'=>array('fr','en'),
'http://www.latrobe.edu.au/agriculture/'=>array('en','eng;'),
'http://earthsoils.calpoly.edu/'=>array('en','eng'),
'http://www.fao.org/foodclimate/hlc-home/en/'=>array('en','fr','es'),
'http://www.bfafh.de/inst2/silvaege.htm'=>array('en','fr','de'),
'http://www.xs4all.nl/~kwanten/'=>array('en','nl'),
'http://www.oznet.ksu.edu/library/hort2/mf2631.pdf'=>array('en','eng;'),
'http://www.fao.org/DOCREP/X7273E/X7273E00.HTM'=>array('en','fr','es'),
'http://pubs.nrc-cnrc.gc.ca/rp-ps/journalDetail.jsp?jcode=cjfr&lang=eng'=>array('en','fr'),
'http://www.bbsrc.ac.uk/funding/grants/agri_food/index.html'=>array('en','eng;'),
'http://www.fao.org/docrep/009/j9256e/j9256e00.htm'=>array('en','fr','es'),
'http://www.asic-cafe.org/'=>array('en','fr'),
'http://www.beehoo.com/'=>array('en','fr'),
'http://www.oecd.org/department/0,3355,en_2649_33901_1_1_1_1_1,00.html'=>array('en','fr'),
'http://www.fao.org/DOCREP/005/Y7581E/Y7581E00.HTM'=>array('en','fr','es','eng;'),
'http://www.fao.org/WAICENT/faoinfo/economic/giews/english/af/index.htm'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Shellfish_Cooking_GMPG.pdf'=>array('en','eng;'),
'http://www.sheepdrove.com'=>array('en','eng;'),
'http://www.fao.org/DOCREP/004/y6000e/y6000e00.htm'=>array('en','fr','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Demersal%20GPG%20WA.pdf'=>array('en','eng;'),
'http://www.acdi-cida.gc.ca/INDEX-E.HTM'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Plaice%20v%201.1.pdf'=>array('en','eng;'),
'http://www.syngenta.com/en/index.aspx'=>array('en','de'),
'http://www.coedcymru.org.uk/index.htm'=>array('en','cy'),
'http://ec.europa.eu/agriculture/events/organic/index_en.htm'=>array('en','fr','de'),
'http://www.sunseed.org.uk/'=>array('en','es'),
'http://www.gmo-safety.eu/en/'=>array('en','de'),
'http://bfw.ac.at/index-en.html'=>array('en','de'),
'http://www.fao.org/docrep/011/i0100e/i0100e00.htm'=>array('en','fr','ru','es'),
'http://www.eucalyptus.com.br/index_eng.html'=>array('en','pt'),
'http://www.fao.org/docrep/w9114e/w9114e01.htm'=>array('en','fr','es'),
'http://ec.europa.eu/agriculture/index_en.htm'=>array('en','el','da','nl','fi','fr','de','it','pt','es','sv'),
'http://www.fao.org/nr/water/aquastat/main/index.stm'=>array('en','fr','es'),
'http://www.fao.org/forestry/outlook/en/'=>array('en','fr','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/BangorUni_Hydrodredge_Final.pdf'=>array('en','eng;'),
'http://www.mnr.gov.on.ca/en/Business/CNFER/'=>array('en','fr'),
'http://www.oznet.ksu.edu/library/hort2/mf2606.pdf'=>array('en','eng;'),
'http://www.feric.ca/en/index.cfm'=>array('en','fr'),
'http://www.msc.org/'=>array('en','fr','es','de'),
'http://www3.agr.gc.ca/apps/infohort/index.cfm?action=dspHome&lang=eng'=>array('en','fr'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Pelagic%20GPG%20WA.pdf'=>array('en','eng;'),
'http://www.montpellier.inra.fr/safe/'=>array('en','fr'),
'http://www.fao.org/easypol/output/'=>array('en','es','fr'),
'http://www.ccamlr.org/'=>array('en','eng;'),
'http://www.ext.vt.edu/pubs/forestry/420-560/420-560.html'=>array('en','eng;'),
'http://www4.agr.gc.ca/AAFC-AAC/display-afficher.do?id=1180623750202'=>array('en','fr'),
'http://www.efsa.europa.eu/EFSA/efsa_locale-1178620753812_1178704673160.htm'=>array('en','de','fr'),
'http://www.mm.helsinki.fi/mmett/english/'=>array('en','fi','sv'),
'http://www.undp.org/'=>array('en','fr','es'),
'http://www.fao.org/docrep/003/y1500e/y1500e00.htm'=>array('en','fr','es'),
'http://sis2.agr.gc.ca/cansis/'=>array('en','fr'),
'http://www.dry-net.org/'=>array('en','fr','es','ru'),
'http://www.eurmscfood.nl/'=>array('en','eng;'),
'http://www.iisd.org/'=>array('en','fr'),
'http://www.ag.ncat.edu/default.asp'=>array('en','eng;'),
'http://www.unep.org/'=>array('en','fr'),
'http://www.defra.gov.uk/environment/gm/fse/background/rationale.htm'=>array('en','eng;'),
'http://www.oznet.ksu.edu/library/hort2/mf2370.pdf'=>array('en','eng;'),
'http://www.fao.org/docrep/010/a1200e/a1200e00.htm'=>array('en','fr','es'),
'http://www.organicagcentre.ca/index_e.asp'=>array('en','fr'),
'http://www.fao.org/docrep/009/a0773e/a0773e00.htm'=>array('en','fr','es'),
'http://www.isafa.it/inglese/inglese.htm'=>array('en','it'),
'http://agclass.nal.usda.gov/agt/agt.shtml'=>array('en','es'),
'http://www.cdr.wisc.edu/'=>array('en','eng;'),
'http://www.fertilizer.org/'=>array('en','ru'),
'http://www.lei.wur.nl/UK/'=>array('en','nl'),
'http://www.unbf.ca/forestry/'=>array('en','eng;'),
'http://www.fao.org/fi/default.asp'=>array('en','fr','es'),
'http://www.fao.org/ag/agl/agll/photolib/toc_e.htm'=>array('en','fr','es'),
'http://www.vitis-vea.de/Englisch/eindex.php'=>array('en','de'),
'http://www.unitedsoybean.org/Default.aspx'=>array('en','eng;'),
'http://www.fao.org/docrep/006/y4683e/y4683e00.htm'=>array('en','fr'),
'http://www.fibl.org/en/homepage.html'=>array('en','de','fr','it'),
'http://www.africamuseum.be/'=>array('en','nl','fr'),
'http://www.defra.gov.uk/corporate/consult/foodfarming.htm'=>array('en','eng;'),
'http://epsilon.slu.se/eindex.html'=>array('en','sv'),
'http://www.itto.int/'=>array('en','fr','es'),
'http://www.gmo-free-regions.org/'=>array('en','de'),
'http://www.usorganicproducts.com/'=>array('en','fr','de','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Key%20Features_Crustacea%20processing%20waste.pdf'=>array('en','eng;'),
'http://www.blackwellpublishing.com/journal.asp?ref=0305-0270&site=1'=>array('en','eng;'),
'http://www.wto.org/english/tratop_e/agric_e/agric_e.htm'=>array('en','es'),
'http://www.wki.fhg.de/english/index.html'=>array('en','de'),
'http://www.foodsector.com'=>array('en','eng;'),
'http://www.unwater.org/flashindex.html'=>array('en','fr','es'),
'http://www.fao.org/ag/AGP/AGPC/doc/pasture/forage.htm'=>array('en','fr','es'),
'http://www.seafish.org/pdf.pl?file=seafish/Documents/Mackerel%20Factsheet2%20A4s.pdf'=>array('en','eng;'),
'http://wineserver.ucdavis.edu/'=>array('en','eng;'),
'http://www.alterra.wur.nl/UK/'=>array('en','nl'),
'http://www.fao.org/es/ESA/Sofa.htm'=>array('en','fr','ru','es'),
'http://www.cpvo.fr/main/en/'=>array('en','fr','de','nl'),
'http://www.fao.org/docrep/T0848E/T0848E00.htm'=>array('en','es'),
'http://www.fao.org/publications/sofi/en/'=>array('en','fr','ru','es'),
'http://cfs.nrcan.gc.ca/?lang=en'=>array('en','fr'),
'http://www.promedmail.org/pls/askus/f?p=2400:1000:78987::::FSP_LANGUAGE_PREFERENCE:en-US'=>array('en','eng'),
'http://www.international.inra.fr/'=>array('en','fr','es'),
'http://www.fao.org/docrep/006/j0563e/j0563e00.htm'=>array('en','fr','es'),
'http://www.hse.gov.uk/agriculture/pdf/fatal0405.pdf'=>array('en','eng'),
'http://www.nifes.no/index.php?page_id=126&lang_id=2'=>array('en','no'),
'http://www.eufic.org/index/en/'=>array('en','eng;'),
'http://www.fao.org/docrep/006/j0083e/j0083e00.htm'=>array('en','fr','es'),
'http://www.defra.gov.uk/wildlife-countryside/ewd/rmnc/pdf/rmnc-report-0704.pdf'=>array('en','eng'),
'http://www.fao.org/trade/index_en.asp'=>array('en','fr','es'),
'http://www.ceja.org/'=>array('en','fr'),
'http://www.fao.org/forestry/cpf/en/'=>array('en','fr','es'),
'http://www.biobeds.info/_Attachments/Pesticide%20Handling%20Areas%20and%20Biobeds%20Manual.pdf'=>array('en','eng;'),
'http://www.fao.org/nr/gen/gen_080502_en.htm'=>array('en','fr','es'),
'http://www.fao.org/nr/land/en/'=>array('en','fr','es'),
'http://www.fao.org/docrep/007/y5650e/y5650e00.htm'=>array('en','fr','es'),
'http://www.avec-poultry.eu/'=>array('en','fr'),
'http://www.oznet.ksu.edu/library/hort2/mf2612.pdf'=>array('en','eng;'),
'http://www.fao.org/docrep/006/y5066e/y5066e00.htm'=>array('en','fr'),
'http://www.oecd.org/topic/0,2686,en_2649_37401_1_1_1_1_37401,00.html'=>array('en','fr'),
'http://www.wto.org/english/tratop_e/sps_e/sps_e.htm'=>array('en','fr','es'),
'http://www.bbsrc.ac.uk/organisation/structures/committees/plant_microbial.html'=>array('en','eng;'),
'http://www.farmcrisisnetwork.org.uk/'=>array('en','eng'),
'http://www.campden.co.uk/'=>array('en','eng;'),
'http://www.fao.org/DOCREP/005/Y1453E/Y1453E00.HTM'=>array('en','fr','es'),
'http://www.ilw.agrl.ethz.ch/'=>array('en','de'),
'http://www.frameweb.org/'=>array('en','fr','es'),
'http://www.brogdale.org/'=>array('en','eng;'),
'http://www.fao.org/economic/ess/world-census-of-agriculture/en/'=>array('en','fr','es'),
'http://www.agrsci.org/'=>array('en','da'),
'http://www.esa.org.uk/'=>array('en','fr','de','it','es'),
'http://cottondb.org/'=>array('en','eng;'),
);
      }
}